-- ==============================================================================
-- Migration: 20261002000003_seed_ujian_2025_2026_gasal.sql
-- Description: Seed the UTS (ETS) schedule of 2025/2026 Gasal, Reguler.
--
-- Source: docs/KONSEP JADWAL ETS GASAL 25-26 + PENGAWAS.xlsx, sheet "Reguler" (semesters
-- I, III and V). Requires 20261002000001_exams.sql. 67 rows. Idempotent: rows that
-- already exist (same year, UTS, program, semester, mata kuliah and kelas) are left alone.
--
-- Generated by a one-off Node script (not checked in) that parsed the sheet, mapped every course to its
-- 2026 kode_mk (PLAN.md §7b; semester I by name) and matched dosen by name. Decisions, on purpose:
--
-- 1. The year 2025/2026 Gasal (20251) is created, NOT active; the app's active year stays 2026/2027.
--    There is no 2025/2026 kuliah schedule, so the DOSEN PENGAMPU column of these exams prints blank
--    and each row shows the "tidak ada lagi di jadwal kuliah" mark until one is entered.
-- 2. The 10 university-run (MKWU) courses have the date 21/10/2025 in the sheet but "UNIVERSITAS"
--    instead of an hour, and an exam is dated only together with its hour, so they are seeded without
--    a date (they list under "Belum dijadwalkan") as one GABUNGAN row each.
-- 3. DASAR-DASAR PSIKOTERAPI (60421011, "semester IV ke atas non kelas") is not in the 2026 course
--    catalog, so it is not seeded. Rows whose course is missing from the live catalog are skipped.
-- 4. Rooms 201 and 202 are added (the sheet uses them; the catalog had 301, 302, 303 and Lab. Kom).
-- 5. A pengawas is the matched dosen, else the name as free text; AKADEMIK stays free text. Dosen who
--    are not in the dosen master as of seeding (JUNI ARATIKA) are free text. Biopsikologi kelas B has no
--    pengawas in the sheet.
-- 6. One keterangan per mata kuliah: the first one the sheet gives (Psikologi Sosial is OFFLINE UJIAN
--    LISAN for both kelas; the sheet leaves kelas B's blank).
-- 7. The hidden sheet "GABUNGAN" (2022/2023 Reguler Khusus, an older concept) is not seeded.
-- The sheet has no clashes between pengawas, rooms or kelas (checked with the app's own rules).
-- ==============================================================================

INSERT INTO academic_years (id, label, is_active)
VALUES ('20251', '2025/2026 Gasal', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO rooms (nama, kapasitas) VALUES ('201', 0), ('202', 0)
ON CONFLICT (nama) DO NOTHING;

-- Match each source dosen to the dosen master by name tokens. A key resolves only when exactly one
-- lecturer matches; otherwise it stays NULL (a defense role is left empty, a pengawas falls back to
-- the name as free text). Temp tables, dropped at the end.
CREATE TEMP TABLE _dosen_src (src text PRIMARY KEY, t1 text NOT NULL, t2 text NOT NULL);
INSERT INTO _dosen_src (src, t1, t2) VALUES
    ('aisyah', 'aisyah', 'aisyah'),
    ('akhyar', 'akhyar', 'akhyar'),
    ('anindya', 'anindya', 'anindya'),
    ('dharma', 'dharma', 'dharma'),
    ('evanytha', 'evanytha', 'evanytha'),
    ('farida_aini', 'farida', 'aini'),
    ('grashinta', 'grashinta', 'grashinta'),
    ('kistyanti', 'kistyanti', 'kistyanti'),
    ('maharani', 'maharani', 'maharani'),
    ('rahmani', 'rahmani', 'rahmani'),
    ('ramadhana', 'ramadhana', 'ramadhana'),
    ('septilla', 'septilla', 'septilla'),
    ('seta', 'seta', 'wicaksana'),
    ('vinaya', 'vinaya', 'vinaya'),
    ('wiroko', 'wiroko', 'wiroko');

CREATE TEMP TABLE _dosen AS
SELECT s.src, CASE WHEN count(l.kode_dosen) = 1 THEN min(l.kode_dosen) END AS kode
FROM _dosen_src s
LEFT JOIN lecturers l ON lower(l.nama) LIKE '%' || s.t1 || '%' AND lower(l.nama) LIKE '%' || s.t2 || '%'
GROUP BY s.src;

INSERT INTO exams (academic_year_id, jenis_ujian, jenis_kelas, semester_ke, kode_mk, kelas, tanggal, jam_mulai, jam_selesai, room_id, pengawas, keterangan_ujian)
SELECT
    '20251', 'uts', 'reguler', v.smt, v.kode, v.kelas, v.tanggal::date, v.mulai::time, v.selesai::time,
    (SELECT r.id FROM rooms r WHERE r.nama = v.room),
    (SELECT COALESCE(jsonb_agg(
                CASE WHEN d.kode IS NOT NULL THEN jsonb_build_object('kode_dosen', d.kode) ELSE jsonb_build_object('nama', t.e ->> 'n') END
                ORDER BY t.o), '[]'::jsonb)
       FROM jsonb_array_elements(v.pengawas::jsonb) WITH ORDINALITY AS t(e, o)
       LEFT JOIN _dosen d ON d.src = t.e ->> 'k'),
    v.ket
FROM (VALUES
    (1, '10012001', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012003', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012004', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012005', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012006', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012007', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012008', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012009', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012010', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '10012002', 'GABUNGAN', NULL, NULL, NULL, NULL, '[]', 'offline'),
    (1, '15113002', 'A', '2025-10-27', '08:00', '10:00', '201', '[{"k":"evanytha","n":"DR. EVANYTHA, M.SI., PSIKOLOG"}]', 'offline'),
    (1, '15113002', 'B', '2025-10-27', '08:00', '10:00', '202', '[{"k":"anindya","n":"ANINDYA DEWI PARAMITA, M.PSI., PSIKOLOG"}]', 'offline'),
    (1, '15123004', 'A', '2025-10-29', '08:00', '10:00', '201', '[{"k":"maharani","n":"MAHARANI ARDI PUTRI, M.SI., PSIKOLOG"}]', 'offline'),
    (1, '15123004', 'B', '2025-10-29', '08:00', '10:00', '202', '[{"k":"anindya","n":"ANINDYA DEWI PARAMITA, M.PSI., PSIKOLOG"}]', 'offline'),
    (1, '15123003', 'A', '2025-10-29', '11:00', '13:00', '301', '[{"k":"aisyah","n":"AISYAH, M.SI"}]', 'offline'),
    (1, '15123003', 'B', '2025-10-29', '11:00', '13:00', '302', '[]', 'offline'),
    (1, '15112004', 'A', '2025-10-30', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (1, '15112004', 'B', '2025-10-30', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (1, '15113005', 'A', '2025-10-31', '08:00', '10:00', '201', '[{"k":"dharma","n":"ANDRI SETIA DHARMA, M.PSI., PSIKOLOG"}]', 'offline'),
    (1, '15113005', 'B', '2025-10-31', '08:00', '10:00', '202', '[{"k":"kistyanti","n":"NI MADE RAI KISTYANTI, M.PSI., PSIKOLOG"}]', 'offline'),
    (3, '15132006', 'A', '2025-10-27', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (3, '15132006', 'B', '2025-10-27', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (3, '15142001', 'A', '2025-10-27', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (3, '15142001', 'B', '2025-10-27', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (3, '15123006', 'A', '2025-10-28', '08:00', '10:00', '201', '[{"k":"farida_aini","n":"FARIDA AINI, M.PSI., PSIKOLOG"}]', 'offline'),
    (3, '15123006', 'B', '2025-10-28', '08:00', '10:00', '202', '[{"k":"grashinta","n":"AULLY GRASHINTA, M.SI., PSIKOLOG"}]', 'offline'),
    (3, '15152009', 'A', '2025-10-28', '11:00', '13:00', '201', '[{"k":"kistyanti","n":"NI MADE RAI KISTYANTI, M.PSI., PSIKOLOG"}]', 'offline'),
    (3, '15152009', 'B', '2025-10-28', '11:00', '13:00', '202', '[{"k":"ramadhana","n":"M. RAMADHANA, M.SI"}]', 'offline'),
    (3, '15133004', 'A', '2025-10-29', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'online'),
    (3, '15133004', 'B', '2025-10-29', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'online'),
    (3, '15152014', 'A', '2025-10-29', '14:00', '16:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (3, '15152014', 'B', '2025-10-29', '14:00', '16:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (3, '15132005', 'A', '2025-10-30', '08:00', '10:00', '201', '[{"k":"evanytha","n":"DR. EVANYTHA, M.SI., PSIKOLOG"}]', 'offline'),
    (3, '15132005', 'B', '2025-10-30', '08:00', '10:00', '202', '[{"k":"kistyanti","n":"NI MADE RAI KISTYANTI, M.PSI., PSIKOLOG"}]', 'offline'),
    (3, '15162010', 'GABUNGAN', '2025-10-30', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (3, '15133008', 'A', '2025-10-31', '08:00', '10:00', '302', '[{"k":"akhyar","n":"MUHAMMAD AKHYAR, M.SI"}]', 'ujian_lisan'),
    (3, '15133008', 'B', '2025-10-31', '08:00', '10:00', '303', '[{"k":"vinaya","n":"DR. VINAYA, M.SI"}]', 'ujian_lisan'),
    (3, '15143007', 'A', '2025-10-31', '13:00', '15:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (3, '15143007', 'B', '2025-10-31', '13:00', '15:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (5, '15152002', 'A', '2025-10-27', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (5, '15152002', 'B', '2025-10-27', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (5, '15152002', 'C', '2025-10-27', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (5, '15152010', 'GABUNGAN', '2025-10-27', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'online'),
    (5, '15152012', 'GABUNGAN', '2025-10-27', '14:00', '16:00', NULL, '[{"n":"AKADEMIK"}]', 'take_home'),
    (5, '15143005', 'A', '2025-10-28', '08:00', '10:00', '301', '[{"k":"anindya","n":"ANINDYA DEWI PARAMITA, M.PSI., PSIKOLOG"}]', 'offline'),
    (5, '15143005', 'B', '2025-10-28', '08:00', '10:00', '302', '[{"k":"wiroko","n":"ENDRO PUSPO WIROKO, M.PSI., PSIKOLOG"}]', 'offline'),
    (5, '15143005', 'C', '2025-10-28', '08:00', '10:00', '303', '[{"k":"kistyanti","n":"NI MADE RAI KISTYANTI, M.PSI., PSIKOLOG"}]', 'offline'),
    (5, '15152007', 'A', '2025-10-28', '11:00', '13:00', '301', '[{"n":"JUNI ARATIKA"}]', 'offline'),
    (5, '15152007', 'B', '2025-10-28', '11:00', '13:00', '302', '[{"k":"septilla","n":"A. EKA SEPTILLA, M.PSI., PSIKOLOG"}]', 'offline'),
    (5, '15152007', 'C', '2025-10-28', '11:00', '13:00', '303', '[{"k":"rahmani","n":"SOFI FITRIA RAHMANI, M.PD"}]', 'offline'),
    (5, '15152003', 'A', '2025-10-29', '08:00', '10:00', '301', '[{"k":"vinaya","n":"DR. VINAYA, M.SI"}]', 'offline'),
    (5, '15152003', 'B', '2025-10-29', '08:00', '10:00', '302', '[{"k":"ramadhana","n":"M. RAMADHANA, M.SI"}]', 'offline'),
    (5, '15152003', 'C', '2025-10-29', '08:00', '10:00', '303', '[{"k":"seta","n":"DR. SETA A. WICAKSANA, M.PSI., PSIKOLOG"}]', 'offline'),
    (5, '15152008', 'A', '2025-10-29', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'project'),
    (5, '15152008', 'B', '2025-10-29', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'project'),
    (5, '15152008', 'C', '2025-10-29', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'project'),
    (5, '15143009', 'A', '2025-10-30', '08:00', '10:00', '301', '[{"k":"anindya","n":"ANINDYA DEWI PARAMITA, M.PSI., PSIKOLOG"}]', 'offline'),
    (5, '15143009', 'B', '2025-10-30', '08:00', '10:00', '302', '[{"k":"anindya","n":"ANINDYA DEWI PARAMITA, M.PSI., PSIKOLOG"}]', 'offline'),
    (5, '15143009', 'C', '2025-10-30', '08:00', '10:00', '303', '[{"k":"farida_aini","n":"FARIDA AINI, M.PSI., PSIKOLOG"}]', 'offline'),
    (5, '15162002', 'A', '2025-10-30', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'online'),
    (5, '15162002', 'B', '2025-10-30', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'online'),
    (5, '15162002', 'C', '2025-10-30', '11:00', '13:00', NULL, '[{"n":"AKADEMIK"}]', 'online'),
    (5, '15153001', 'A', '2025-10-31', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'project'),
    (5, '15153001', 'B', '2025-10-31', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'project'),
    (5, '15153001', 'C', '2025-10-31', '08:00', '10:00', NULL, '[{"n":"AKADEMIK"}]', 'project'),
    (5, '15152011', 'A', '2025-10-31', '13:00', '15:00', NULL, '[{"n":"AKADEMIK"}]', 'project'),
    (5, '15152011', 'B', '2025-10-31', '13:00', '15:00', NULL, '[{"n":"AKADEMIK"}]', 'project')
) AS v(smt, kode, kelas, tanggal, mulai, selesai, room, pengawas, ket)
WHERE EXISTS (SELECT 1 FROM courses c WHERE c.kode_mk = v.kode)
ON CONFLICT ON CONSTRAINT uq_exams DO NOTHING;

DROP TABLE _dosen;
DROP TABLE _dosen_src;
