-- ==============================================================================
-- Migration: 20261002000004_seed_sidang_2025_2026_gasal.sql
-- Description: Seed the prasidang and sidang schedule of 2025/2026 Gasal.
--
-- Sources: docs/Jadwal Prasidang Gasal 2025-2026.xlsx (15 mahasiswa, 24-25 Nov 2025, kelompok 1-3)
-- and docs/jadwal sidang master.xlsx (12 mahasiswa, 3 Feb 2026, ruang 301-303). Requires
-- 20261002000002_defenses.sql. Idempotent: a mahasiswa already scheduled for that jenis in that year
-- (same NPM) is left alone.
--
-- Generated by a one-off Node script (not checked in) that parsed both sheets and matched dosen by name.
-- Decisions, on purpose:
--
-- 1. The year 2025/2026 Gasal (20251) is created, NOT active (the sidang of 3 Feb 2026 is titled Gasal in
--    its source). Empty slots in the sheets (no mahasiswa) are not seeded.
-- 2. Dosen are matched to the dosen master by name when this runs. A role whose dosen is not in the master
--    (or matches more than one) is left empty instead of guessed; fill it in on /sidang after adding the
--    dosen. Against the dosen seeded by 20260922000002, every dosen in these sheets resolves.
-- 3. The external examiner (sidang Penguji I) is free text, as typed in the sheet: Prof. Farida Kurniawati,
--    Dr. Ade Iva Murty, Dr. Eva Septiana, Dr. Lucia RM Royanto and Prof. Dr. Awaluddin Tjalla. It stays
--    text even for a name that is also in the dosen master (Awaluddin Tjalla is), as the field always is.
-- 4. Names and titles are kept as typed in the sheets (the printed sheets use title case).
-- 5. The sheets have no clashes between dosen, external examiners or rooms (checked with the app's rules).
-- ==============================================================================

INSERT INTO academic_years (id, label, is_active)
VALUES ('20251', '2025/2026 Gasal', false)
ON CONFLICT (id) DO NOTHING;

-- Match each source dosen to the dosen master by name tokens. A key resolves only when exactly one
-- lecturer matches; otherwise it stays NULL (a defense role is left empty, a pengawas falls back to
-- the name as free text). Temp tables, dropped at the end.
CREATE TEMP TABLE _dosen_src (src text PRIMARY KEY, t1 text NOT NULL, t2 text NOT NULL);
INSERT INTO _dosen_src (src, t1, t2) VALUES
    ('aisyah', 'aisyah', 'aisyah'),
    ('akhyar', 'akhyar', 'akhyar'),
    ('anindya', 'anindya', 'anindya'),
    ('bimo', 'bimo', 'wikant'),
    ('dharma', 'dharma', 'dharma'),
    ('evanytha', 'evanytha', 'evanytha'),
    ('farida_aini', 'farida', 'aini'),
    ('grashinta', 'grashinta', 'grashinta'),
    ('kistyanti', 'kistyanti', 'kistyanti'),
    ('maharani', 'maharani', 'maharani'),
    ('nindyati', 'nindyati', 'nindyati'),
    ('ramadhana', 'ramadhana', 'ramadhana'),
    ('septilla', 'septilla', 'septilla'),
    ('seta', 'seta', 'wicaksana'),
    ('silverius', 'silverius', 'soeharso'),
    ('suwandi', 'suwandi', 'suwandi'),
    ('vinaya', 'vinaya', 'vinaya'),
    ('wiroko', 'wiroko', 'wiroko');

CREATE TEMP TABLE _dosen AS
SELECT s.src, CASE WHEN count(l.kode_dosen) = 1 THEN min(l.kode_dosen) END AS kode
FROM _dosen_src s
LEFT JOIN lecturers l ON lower(l.nama) LIKE '%' || s.t1 || '%' AND lower(l.nama) LIKE '%' || s.t2 || '%'
GROUP BY s.src;

INSERT INTO defenses (academic_year_id, jenis, tanggal, jam_mulai, jam_selesai, room_id, kelompok, npm, nama_mahasiswa, judul_skripsi, pembimbing_kode, penguji_kode, penguji_eksternal)
SELECT
    '20251', v.jenis, v.tanggal::date, v.mulai::time, v.selesai::time,
    (SELECT r.id FROM rooms r WHERE r.nama = v.ruang),
    v.kelompok::smallint, v.npm, v.nama, v.judul,
    (SELECT d.kode FROM _dosen d WHERE d.src = v.pb),
    (SELECT d.kode FROM _dosen d WHERE d.src = v.pj),
    v.eksternal
FROM (VALUES
    ('prasidang', '2025-11-24', 1, NULL, '10:30', '11:30', '6021210068', 'Fadhlan Wibisono H', 'Hubungan Antara Future Anxiety Dengan Quality Of Life Pada Generasi Z Di Indonesia', 'dharma', 'maharani', ''),
    ('prasidang', '2025-11-24', 1, NULL, '13:00', '14:00', '6022210039', 'Jihan Shabrina Feby Amelia', 'Peran Help Seeking Behavior Melalui (Website Beranibersuara.Id) Terhadap Online Sexual Harassment', 'aisyah', 'anindya', ''),
    ('prasidang', '2025-11-24', 1, NULL, '14:30', '15:30', '6022210059', 'Najwa Prajna Phalita Kurniawan', 'Peran Social Comparison Dan Social Media Rumination Dalam Memprediksi Social Media Addiction Pada Remaja', 'anindya', 'evanytha', ''),
    ('prasidang', '2025-11-24', 2, NULL, '09:00', '10:00', '6021210064', 'Saniy Saffanah T', 'Pengaruh Social Support Dan Social Comparison Terhadap Career Anxiety Pada Fresh Graduate Emerging Adult', 'evanytha', 'silverius', ''),
    ('prasidang', '2025-11-24', 2, NULL, '10:30', '11:30', '6021210087', 'Wardah Yasmine Shakila Mahdar', 'Hubungan Self Regulation Dan Academic Buoyancy Pada Mahasiswa Gen Z Dengan Problematic Social Media Use', 'suwandi', 'silverius', ''),
    ('prasidang', '2025-11-24', 2, NULL, '13:00', '14:00', '6020210070', 'Muchammad Haikal Bichaq', 'Hubungan Antara Self Discrepancy Dengan Perilaku Impulsive Buying Pada Cosplayer Dewasa Muda', 'ramadhana', 'evanytha', ''),
    ('prasidang', '2025-11-25', 1, NULL, '09:00', '10:00', '6020210088', 'Injie Zahwa Aulia', 'Peran Pemberdayaan Psikologis Terhadap OCB (Organizational Citizenship Behavior) Pada Karyawan Kopi Kina', 'wiroko', 'seta', ''),
    ('prasidang', '2025-11-25', 1, NULL, '10:30', '11:30', '6019210059', 'Ichlasun Naas Ibrahiem', 'Peran Kepribadian Proaktif Terhadap Self-Perceived Employability Pada Pekerja Industri Manufaktur', 'wiroko', 'nindyati', ''),
    ('prasidang', '2025-11-25', 1, NULL, '13:00', '14:00', '6022210038', 'Ramdan Malik Prawira', 'Gambaran Burnout Pada Pegawai Dinas Kependudukan Dan Pencatatan Sipil (Dukcapil) Kota Depok', 'bimo', 'nindyati', ''),
    ('prasidang', '2025-11-25', 2, NULL, '08:00', '09:00', '6021210017', 'Alfia Rizkyani', 'Hubungan Problematic Online Game Use (Pogu) Dengan Kualitas Tidur Pada Gen Z Pemain Game Roblox', 'aisyah', 'grashinta', ''),
    ('prasidang', '2025-11-25', 2, NULL, '10:30', '11:30', '6022210071', 'Larashaty Putri Prameswari', 'Pengaruh Adverse Childhood Experiences Dan Social Media Rumination Terhadap Social Media Addiction Pada Remaja', 'anindya', 'aisyah', ''),
    ('prasidang', '2025-11-25', 2, NULL, '13:00', '14:00', '6019210047', 'Ulva Andini', 'Hubungan Antara Romantic Love Myth Dengan Cyber Dating Violence Pada Emerging Adults Korban Kekerasan Dalam Pacaran', 'akhyar', 'maharani', ''),
    ('prasidang', '2025-11-25', 2, NULL, '14:30', '15:30', '6020210081', 'Fildza Wafiq Ghasani', 'Hubungan Self Esteem Dengan Komitmen Pernikahan Pada Dewasa Yang Berselingkuh', 'septilla', 'aisyah', ''),
    ('prasidang', '2025-11-25', 3, NULL, '13:00', '14:00', '6021210051', 'Aurelia Bilbina', 'Pengaruh Dukungan Sosial dan Kebersyukuran terhadap Resiliensi Pada Penderita Lupus Fase Emerging Adulthood', 'evanytha', 'seta', ''),
    ('prasidang', '2025-11-25', 3, NULL, '14:30', '15:30', '6022210067', 'Aisyah Kenia Fadyah', 'Peran Self-Esteem Dan Self-Disclosure Terhadap Tingkat Intimacy Dalam Hubungan Romantis Melalui Dating Apps Pada Emerging Adulthood', 'kistyanti', 'anindya', ''),
    ('sidang', '2026-02-03', NULL, '301', '08:00', '10:00', '6019210059', 'Ichlasun Naas Ibrahiem', 'Peran Kepribadian Proaktif Terhadap Self-Perceived Employability Pada Pekerja Industri Manufaktur', 'wiroko', 'anindya', 'Dr. Eva Septiana, M.Si., Psikolog'),
    ('sidang', '2026-02-03', NULL, '301', '11:00', '13:00', '6020210121', 'Tiara Pragati Wira Anggini', 'Pengaruh Environmental Knowledge dengan Green Cosmetics Purchase Intention pada Perempuan Emerging Adulthood di Jabodetabek', 'dharma', 'nindyati', 'Dr. Ade Iva Murty, M.Si'),
    ('sidang', '2026-02-03', NULL, '301', '13:00', '15:00', '6019210044', 'Indah Safitri Ningrum', 'Peran Self Esteem Terhadap Romantic Jealousy Pada Individu Early Adulthood Yang Menikah', 'maharani', 'aisyah', 'Dr. Ade Iva Murty, M.Si'),
    ('sidang', '2026-02-03', NULL, '301', '15:00', '17:00', '6019210097', 'Feni Setianingsih', 'Hubungan Attachment Style dengan Fear of Commitment pada Generasi Z yang Memilih Hubungan Tanpa Status (Situationships)', 'maharani', 'evanytha', 'Prof. Farida Kurniawati, M.Sp.Ed., Ph.D'),
    ('sidang', '2026-02-03', NULL, '302', '08:00', '10:00', '6019210047', 'Ulva Andini', 'Hubungan Antara Romantic Love Myth Dengan Dating Violence Pada Emerging Adults Korban Kekerasan Dalam Pacaran', 'vinaya', 'maharani', 'Prof. Dr. Awaluddin Tjalla, M.Pd'),
    ('sidang', '2026-02-03', NULL, '302', '10:00', '12:00', '6020210093', 'Salma Novita Rachma Danty', 'Gambaran Stage Of Grief Pada Istri Pasca Kematian Pasangan Hidup Akibat Kanker Paru-Paru', 'septilla', 'seta', 'Prof. Dr. Awaluddin Tjalla, M.Pd'),
    ('sidang', '2026-02-03', NULL, '302', '13:00', '15:00', '6021210058', 'Savitri Nurhalizah', 'Hubungan Loneliness dan Perilaku Agresi Pada Emerging Adulthood Yang Menjalani Long Distance Relationship', 'kistyanti', 'wiroko', 'Prof. Farida Kurniawati, M.Sp.Ed., Ph.D'),
    ('sidang', '2026-02-03', NULL, '302', '15:00', '17:00', '6021210017', 'Alfia Rizkyani', 'Peran Problematic Online Game Use (Pogu) Terhadap Kualitas Tidur Pada Gen Z Pemain Game Roblox', 'aisyah', 'vinaya', 'Dr. Ade Iva Murty, M.Si'),
    ('sidang', '2026-02-03', NULL, '303', '08:00', '10:00', '6021210010', 'Nicolas Immanuel Wong', 'Hubungan Fear of Missing Out dengan Intensitas Keinginan Melakukan Aktivitas Olahraga pada Remaja Akhir di Kabupaten Bogor', 'seta', 'evanytha', 'Prof. Farida Kurniawati, M.Sp.Ed., Ph.D'),
    ('sidang', '2026-02-03', NULL, '303', '10:00', '12:00', '6021210005', 'Ezra Raistan Koral', 'Hubungan Dukungan Sosial dan Burnout Pada Shadow Teacher Pendamping Anak Autis Di Sekolah Inklusi', 'farida_aini', 'grashinta', 'Prof. Farida Kurniawati, M.Sp.Ed., Ph.D'),
    ('sidang', '2026-02-03', NULL, '303', '13:00', '15:00', '6021210080', 'Moch. Rafi Rachman', 'Hubungan Intolerance Of Uncertainty Terhadap Academic Stress Pada Mahasiswa Semester Akhir', 'farida_aini', 'grashinta', 'Dr. Lucia RM Royanto, M.Si, Sp.Ed., Psikolog'),
    ('sidang', '2026-02-03', NULL, '303', '15:00', '17:00', '6021210087', 'Wardah Yasmine Shakila Mahdar', 'Hubungan Self Regulation dan Academic Buoyancy Pada Mahasiswa Gen Z Dengan Problematic Social Media Use', 'grashinta', 'silverius', 'Prof. Dr. Awaluddin Tjalla, M.Pd')
) AS v(jenis, tanggal, kelompok, ruang, mulai, selesai, npm, nama, judul, pb, pj, eksternal)
ON CONFLICT (academic_year_id, jenis, npm) DO NOTHING;

DROP TABLE _dosen;
DROP TABLE _dosen_src;
